# -*- coding: utf-8 -*-
"""Python_practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wdKGNadm9LamRl_yfO5J-pmGScKMuvRE
"""

print("Hello World!")

a_variable  = "String"
 print(a_variable)
 type(a_variable)

""" This is a multi line comment """

string_example = "Hello! My name is Dishant"
sub_string = string_example[0:5]
print(sub_string)



example_dict = {1: "Dishant", 2: "Khanna"}
print(example_dict[2])

list_example = [1,2,3,4,5,6]
for i in list_example:
  print(i)

for i in i < 10 not i >0:
  print(i)

string_example1 = "Hello World!"
print(string_example1[-1:0])

for i in range(10):
  print("This number is  {0} next is {1}".format(i, "String"))

len(list_example)
print(list_example)
print(len(list_example))

i = 10

if i < 10: 
  print(False)
elif i == 10:
  print(True)
else:
  if i <15:
    print(True)
  else:
d    print(False)

def myFunction(i: int) -> int:
  return i+1


if __name__ == "__app__":


if _name__ == "__main__":
i = 10
a = myFunction(i)
print(a)

list_example2 = [1,2,3,4,5,6]
list_example3 = [i+1 for i in list_example2]
print(list_example3)
dict_example2 = {1:10, 2:20, 3:30, 4:40}
dict_example3 = {value:key for key, value in dict_example2.items()}
print(dict_example3)

i

i = 0
while i < 10:
  print(i)
  i += 1